### ISSUE TITLE
adts sampling_frequency_index error value

### ISSUE THREAD

**Issue by roger912** [shaozg/adts#2]
unsigned char sampling_frequency_index: 4;  is & 0x0F, but adts.c is & 0x0e

get_fixed_header()
header->sampling_frequency_index = (adts >> 34) & 0x0e;
fix:
header->sampling_frequency_index = (adts >> 34) & 0x0f;

convert_adts_header2int64()
ret_value |= (fixed_header->sampling_frequency_index) & 0x0e;
fix:
ret_value |= (fixed_header->sampling_frequency_index) & 0x0f;

**Comment by shaozg** [comment]
Thanks!
